tello_terrain_follow_node:
  ros__parameters:
    target_distance: 1.0
    kp: 0.75
    ki: 0.02
    kd: 0.05
    max_vel: 1.0
    min_vel: -1.0
    compensate_for_pitch: false
    rel_alt_topic:  "/tello/relative_altitude"
    offset_topic: "/tello/offset_from_target"
    odom_topic: "/tello/odom"
    cmd_vel: "/terrain_follow/cmd_vel"